### ISSUE TITLE
 STMeta Dataset

### ISSUE THREAD

**Issue by L-Vickliet** [uctb/UCTB#9]
An error occurs when I run the /UCTB/Experiments/CustomizedDemo:
that is:
{'graph': 'TopK', 'MergeIndex': '12'}
Downloading data into ~/anaconda3/envs/UCTB/lib/python3.6/site-packages/UCTB/data
HTTP Error 404: Not Found

I checked that I can't download metro_shanghai dataset, how can I obtain this dataset?

**Comment by Liyue-Chen** [comment]
> An error occurs when I run the /UCTB/Experiments/CustomizedDemo:
> that is:
> {'graph': 'TopK', 'MergeIndex': '12'}
> Downloading data into ~/anaconda3/envs/UCTB/lib/python3.6/site-packages/UCTB/data
> HTTP Error 404: Not Found
> 
> I checked that I can't download metro_shanghai dataset, how can I obtain this dataset?

Hi, Vickliet~
I'm sorry to tell you that the Metro Shanghai dataset couldn't be open since we haven't got the licenses to release it. 

If you want to perform GNNs on your customized graphs, you could modify the data loader parameters and conduct experiments on the Bike datasets. 

If you want to obtain metro crowd flow data, we recommend you collect it on your own. Recently, a website provides the metro crowd flow data in Beijing. See the  `https://bjsubway.jinzihao.me/` for more details.
